#!/bin/bash

: ${LOGFILE:=/tmp/insall_agent.log}
: ${DEBUG:=1}

main() {
  debug "Installing Kerberos client"
  yum install -y krb5-workstation
}

debug(){
  [[ "$DEBUG" ]] && echo "[DEBUG] $*" >> $LOGFILE
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@"
